default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: web_dev_final_development
  username: postgres
  password: 1
  host: localhost

test:
  <<: *default
  database: web_dev_final_test
  username: postgres 
  password: 1
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

